title:             Nghi's blog
email:             ptnghi@apcs.vn
description:       A blog to write about stuff I learned and read
author:            ptnghi
baseurl:           "/"
url:               "http://ptnghi.github.io"

# Social Profiles
twitter_username:  
github_username:   ptnghi
facebook_username: ptnghiapcs

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
