title:             Nghi's blog
email:             ptnghi@apcs.vn
description:       A blog to write about stuff I read
author:            ptnghi
baseurl:           "/"
url:               "http://ptnghi.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
